### ISSUE TITLE
Make whole box clickable on each item (home page)

### ISSUE THREAD

**Issue by mjboylson** [joeboylson/mb-portfolio#10]
For example, the image and the title/caption should click to the portfolio page it is referring to. Like it should be clickable all the way over to the cursor in the screesnhot attached.

![image](https://user-images.githubusercontent.com/16639132/71127850-d7b74500-21b9-11ea-9636-42631f0fec72.png)

**Comment by joeboylson** [comment]
I adjusted the grid just a bit (mentioned my fix in #8 ) because it was off-centered. The project item should now reach all the way out.
