### ISSUE TITLE
Education/Experience

### ISSUE THREAD

**Issue by mjboylson** [joeboylson/mb-portfolio#4]
Please move this type over tp the right of the description text. See mockup if confused.

**Comment by joeboylson** [comment]
![AboutPage](https://user-images.githubusercontent.com/34290408/69156419-59c82700-0ab1-11ea-9691-8bae8804c6db.jpg)

**Comment by joeboylson** [comment]
Alright, fixed the alignment on this one.

**Comment by joeboylson** [comment]
https://github.com/joeboylson/mb-portfolio/commit/e6b1538a99251b217d2ff0cde4c7025774d83b21
