### ISSUE TITLE
Things I'd Like to Do is Empty

### ISSUE THREAD

**Issue by mjboylson** [joeboylson/mb-portfolio#5]

**Comment by joeboylson** [comment]
![AboutPage](https://user-images.githubusercontent.com/34290408/69157949-ac0a4780-0ab3-11ea-9a35-823e603f6a1d.jpg)

**Comment by joeboylson** [comment]
The mockup I was looking at was old. This section was previously just a copy of "Things I've Done" so I left it empty for the time being.

Filled it out with the updated info.

**Comment by joeboylson** [comment]
https://github.com/joeboylson/mb-portfolio/commit/e6b1538a99251b217d2ff0cde4c7025774d83b21
